version: '3.2'

services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/large-body.conf:/etc/nginx/conf.d/large-body.conf:ro
    networks:
      - webproxy

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE     : 'db'
      MYSQL_USER         : 'user'
      MYSQL_PASSWORD     : 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - internal
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: finwo/adminer
    ports:
      - 4000:8080
    depends_on:
      - mysql
    networks:
      - webproxy
      - internal
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=adminer.docker

  # api:
  #   env_file:
  #     - env.dev
  #   build: server
  #   restart: always
  #   depends_on:
  #     - mysql
  #   environment:
  #     PORT: 5010
  #     DATABASE_URL: 'mysql://user:password@mysql/db'
  #   ports:
  #     - '5010:5010'

  # client:
  #   build: client
  #   restart: always
  #   depends_on:
  #     - api
  #   environment:
  #     PORT: 5000
  #     API_HOST: localhost:5010
  #   ports:
  #     - '5000:80'

networks:
  internal:
    driver: bridge
  webproxy:
    driver: bridge

volumes:
  db_data:
